apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: null
  name: lb-deploy-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: lb-test-app
status:
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0
